baseurl = "https://www.kamesuta.com/"
canonifyURLs = false
defaultContentLanguage = "ja"
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
languageCode = "ja-JP"
paginate = 7
rssLimit = 10
hasCJKLanguage = true
publishDir = "./../../../public"

# add redirects/headers
[outputs]
  home = ["HTML", "RSS"]

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"

#[permalinks]
#  blog = "/blog/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "date"
    weight = 10
